spring:  
  cloud:
    gateway:
      routes:
      - id: inventory_route
        uri: http://${nagarro.inventory-service}/inventory
        predicates:
        - Path=/inventory/{segment}
        
      - id: order_route
        uri: http://${nagarro.order-service}/order
        predicates:
        - Path=/order/{segment}
        
      - id: user_route
        uri: http://${nagarro.user-service}/user
        predicates:
        - Path=/user/{segment}
