spring:  
  cloud:
    gateway:
      routes:
      - id: inventory_route
        uri: http://${nagarro.inventory-service}/catalogue
        predicates:
        - Path=/catalogue/**
        filters:
        - RewritePath=$\{segment}
        
      - id: order_route
        uri: http://${nagarro.order-service}/order
        predicates:
        - Path=/order/**
        
      - id: user_route
        uri: http://${nagarro.user-service}/user
        predicates:
        - Path=/user/**
