spring:
  datasource:
    url: jdbc:mysql://${nagarro.mysql-server}/orders

  cloud:
    stream:
      bindings:
        orderRequest-out-0:
          destination: order
          
        orderRequestTimedOut-out-0:
          destination: order
          
        orderItemsAvailable-in-0:
          group: order-service
          destination: order
          
        orderItemsNotAvailable-in-0:
          group: order-service
          destination: order
